-- OpsMuster — initial schema
-- All PKs are UUIDs generated by gen_random_uuid() (no uuid-ossp needed in PG 13+).
-- All timestamps are TIMESTAMPTZ.
-- FKs use RESTRICT unless stated otherwise.

-- ============================================================
-- Users
-- ============================================================

CREATE TABLE users (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email          TEXT NOT NULL UNIQUE,
    display_name   TEXT NOT NULL,
    role           TEXT NOT NULL CHECK (role IN ('admin', 'staff', 'user')),
    password_hash  TEXT NOT NULL DEFAULT '',
    mfa_secret     TEXT NOT NULL DEFAULT '',
    mfa_enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    saml_subject   TEXT NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);

CREATE INDEX users_email_idx ON users (email);
CREATE INDEX users_saml_subject_idx ON users (saml_subject) WHERE saml_subject != '';

-- ============================================================
-- CTI Hierarchy
-- ============================================================

CREATE TABLE categories (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active     BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE types (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE items (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type_id    UUID NOT NULL REFERENCES types (id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active     BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- Groups and Scopes
-- ============================================================

CREATE TABLE groups (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE group_members (
    group_id UUID NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    user_id  UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

-- A group can own all types in a category (type_id IS NULL) or a specific type.
-- The unique index uses COALESCE so that (group, category, NULL) and
-- (group, category, NULL) are treated as duplicates — two NULLs are equal.
CREATE TABLE group_scopes (
    group_id    UUID NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    type_id     UUID REFERENCES types (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX group_scopes_unique ON group_scopes (
    group_id, category_id, COALESCE(type_id, '00000000-0000-0000-0000-000000000000'::UUID)
);

-- ============================================================
-- Statuses
-- ============================================================

CREATE TABLE statuses (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT NOT NULL UNIQUE,
    kind       TEXT NOT NULL DEFAULT 'custom' CHECK (kind IN ('system', 'custom')),
    sort_order INTEGER NOT NULL DEFAULT 0,
    color      TEXT NOT NULL DEFAULT '#6b7280'
);

-- Seed system statuses. IDs are fixed so that other code can rely on name lookups.
INSERT INTO statuses (name, kind, sort_order, color) VALUES
    ('New',         'system', 1,  '#6366f1'),
    ('In Progress', 'custom', 2,  '#f59e0b'),
    ('Pending',     'custom', 3,  '#8b5cf6'),
    ('Resolved',    'system', 98, '#10b981'),
    ('Closed',      'system', 99, '#6b7280');

-- ============================================================
-- Tickets
-- ============================================================

CREATE SEQUENCE ticket_seq START 1;

CREATE TABLE tickets (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tracking_number  TEXT NOT NULL UNIQUE,
    subject          TEXT NOT NULL,
    description      TEXT NOT NULL DEFAULT '',
    category_id      UUID NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
    type_id          UUID REFERENCES types (id) ON DELETE RESTRICT,
    item_id          UUID REFERENCES items (id) ON DELETE RESTRICT,
    priority         TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),
    status_id        UUID NOT NULL REFERENCES statuses (id) ON DELETE RESTRICT,
    assignee_user_id  UUID REFERENCES users (id) ON DELETE SET NULL,
    assignee_group_id UUID REFERENCES groups (id) ON DELETE SET NULL,
    reporter_user_id  UUID REFERENCES users (id) ON DELETE SET NULL,
    guest_email      TEXT,
    resolution_notes TEXT,
    resolved_at      TIMESTAMPTZ,
    closed_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ticket_reporter_or_guest CHECK (
        reporter_user_id IS NOT NULL OR guest_email IS NOT NULL
    )
);

CREATE INDEX tickets_reporter_idx ON tickets (reporter_user_id) WHERE reporter_user_id IS NOT NULL;
CREATE INDEX tickets_assignee_user_idx ON tickets (assignee_user_id) WHERE assignee_user_id IS NOT NULL;
CREATE INDEX tickets_assignee_group_idx ON tickets (assignee_group_id) WHERE assignee_group_id IS NOT NULL;
CREATE INDEX tickets_status_idx ON tickets (status_id);

-- ============================================================
-- Ticket Links
-- ============================================================

CREATE TABLE ticket_links (
    source_ticket_id UUID NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    target_ticket_id UUID NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    link_type        TEXT NOT NULL CHECK (link_type IN ('related_to', 'parent_child', 'caused_by', 'duplicate_of')),

    -- Prevent duplicate bidirectional links by canonicalising order.
    CONSTRAINT ticket_links_no_self_link CHECK (source_ticket_id != target_ticket_id),
    CONSTRAINT ticket_links_unique UNIQUE (
        source_ticket_id,
        target_ticket_id,
        link_type
    )
);

-- ============================================================
-- Ticket Replies
-- ============================================================

CREATE TABLE ticket_replies (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id   UUID NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    author_id   UUID REFERENCES users (id) ON DELETE SET NULL,
    guest_token TEXT,
    body        TEXT NOT NULL,
    internal    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ticket_replies_ticket_idx ON ticket_replies (ticket_id);

-- ============================================================
-- Attachments
-- ============================================================

CREATE TABLE attachments (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id    UUID NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    filename     TEXT NOT NULL,
    mime_type    TEXT NOT NULL,
    size_bytes   BIGINT NOT NULL,
    storage_path TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX attachments_ticket_idx ON attachments (ticket_id);

-- ============================================================
-- SLA Policies and Records
-- ============================================================

CREATE TABLE sla_policies (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  TEXT NOT NULL,
    priority              TEXT NOT NULL CHECK (priority IN ('critical', 'high', 'medium', 'low')),
    category_id           UUID REFERENCES categories (id) ON DELETE CASCADE,
    response_target_min   INTEGER NOT NULL,
    resolution_target_min INTEGER NOT NULL
);

CREATE TABLE sla_records (
    ticket_id               UUID PRIMARY KEY REFERENCES tickets (id) ON DELETE CASCADE,
    policy_id               UUID NOT NULL REFERENCES sla_policies (id) ON DELETE RESTRICT,
    first_response_at       TIMESTAMPTZ,
    resolved_at             TIMESTAMPTZ,
    response_breached_at    TIMESTAMPTZ,
    resolution_breached_at  TIMESTAMPTZ
);

-- ============================================================
-- Audit Log
-- ============================================================

CREATE TABLE audit_log (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id    UUID REFERENCES users (id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id   UUID NOT NULL,
    action      TEXT NOT NULL,
    before      JSONB,
    after       JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_log_entity_idx ON audit_log (entity_type, entity_id);

-- ============================================================
-- Plugins
-- ============================================================

CREATE TABLE plugins (
    id           TEXT PRIMARY KEY,   -- reverse-DNS, e.g. "com.example.slack"
    name         TEXT NOT NULL,
    version      TEXT NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    author       TEXT NOT NULL DEFAULT '',
    runtime      TEXT NOT NULL CHECK (runtime IN ('native', 'wasm')),
    hooks        TEXT[] NOT NULL DEFAULT '{}',
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    wasm_path    TEXT NOT NULL DEFAULT '',
    installed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Webhook Configs
-- ============================================================

CREATE TABLE webhook_configs (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url        TEXT NOT NULL,
    events     TEXT[] NOT NULL DEFAULT '{}',
    secret     TEXT NOT NULL DEFAULT '',   -- HMAC secret for payload signing
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- API Keys
-- ============================================================

CREATE TABLE api_keys (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name         TEXT NOT NULL,
    hashed_token TEXT NOT NULL UNIQUE,
    user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    scopes       TEXT[] NOT NULL DEFAULT '{}',
    last_used_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX api_keys_hashed_token_idx ON api_keys (hashed_token);

-- ============================================================
-- OAuth2 Clients (client credentials grant)
-- ============================================================

CREATE TABLE oauth_clients (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id     TEXT NOT NULL UNIQUE,
    hashed_secret TEXT NOT NULL,
    name          TEXT NOT NULL,
    scopes        TEXT[] NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Settings (key/value, values are JSONB)
-- ============================================================

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value JSONB NOT NULL
);

INSERT INTO settings (key, value) VALUES
    ('saml_enabled',            'false'),
    ('guest_submission_enabled','false'),
    ('sla_enabled',             'false'),
    ('mfa_enabled',             'false'),
    ('mfa_enforced_roles',      '[]'),
    ('reopen_window_days',      '7'),
    ('reopen_target_status_name', '"New"');
