name: Deploy to vinnie

on:
  push:
    branches: [main]
    paths:
      - backend/**
      - frontend/**
      - docker/**
      - go.mod
      - go.sum

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          git -C ~/docker/gohelpdesk pull
          cd ~/docker/gohelpdesk/docker
          docker compose up -d --build
