name: Deploy to vinnie

on:
  push:
    branches: [main]
    paths:
      - backend/**
      - frontend/**
      - docker/**
      - go.mod
      - go.sum
      - .github/workflows/deploy.yml

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          git -C ~/docker/opsmuster pull
          cd ~/docker/opsmuster/docker
          docker compose up -d --build
